apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: artifact-from-git-
spec:
  entrypoint: artifact-from-git
  templates:
    - name: artifact-from-git
      inputs:
        artifacts:
          - name: apis
            path: /workspace
            git:
              repo: https://github.com/apirator/workflow-api-docs.git
              revision: "main"
      container:
        image: debian
        command: [sh, -c]
        args: ["ls -l /workspace "]
