apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: check-api-wf-
spec:
  entrypoint: check-api
  arguments:
    parameters:
      - name: location
        value: "workspace/apis/players-v1.yaml"
      - name: error_on
        value: error
        ## error, warn,info and hint
  workflowTemplateRef:
    name: check-api-wt
