apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: create-documentation-wf-
spec:
  entrypoint: openapi-doc
  arguments:
    parameters:
      - name: branch
        value: players-v5
      - name: new_api_location
        value: "workspace/apis/players-v5.yaml"
      - name: destination_folder
        value: "/tmp/players.html"
      - name: api_name
        value: players
  workflowTemplateRef:
    name: documentation-api-wt
