apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: extract-wf-
spec:
  entrypoint: extract
  arguments:
    parameters:
      - name: branch
        value: players-v10
      - name: modified
        value: "/apis/players-v10.yaml"
  workflowTemplateRef:
    name: extract-wt
