apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: api-production-wf-
spec:
  entrypoint: api-production-flow
  arguments:
    parameters:
      - name: branch
        value: players-v5
      - name: location
        value: "workspace/apis/players-v5.yaml"
      - name: error_on
        value: error
      - name: new_api_location
        value: "workspace/apis/players-v5.yaml"
      - name: destination_folder
        value: "/tmp/players.html"
      - name: oas
        value: "/workspace/apis/players-v5.yaml"
      - name: ingress
        value: /tmp
      - name: service
        value: players-v5
      - name: commit_message
        value: "players API V5"
      - name: api_name
        value: "players-v5"
  templates:
    - name: api-production-flow
      steps:
        - - name: check-api
            templateRef:
              name: check-api-wt
              template: check-api
            input:
              parameters:
                - name: branch
                  value: players-v5
        - - name: catalog-api
            templateRef:
              name: api-catalog-wt
              template: api-catalog
            input:
              parameters:
                - name: branch
                  value: players-v5
        - - name: document-api
            templateRef:
              name: documentation-api-wt
              template: openapi-doc
            input:
              parameters:
                - name: branch
                  value: players-v5
        - - name: deploy-api
            templateRef:
              name: create-ingress-wt
              template: create-ingress
            input:
              parameters:
                - name: branch
                  value: players-v5
        - - name: create-pr
            templateRef:
              name: create-api-pr-production-wt
              template: create-pr
            input:
              parameters:
                - name: branch
                  value: players-v5
            arguments:
              artifacts:
                - name: catalog-file
                  from: "{{steps.catalog-api.outputs.artifacts.catalog}}"
                - name: deploy-file
                  from: "{{steps.deploy-api.outputs.artifacts.ingress}}"
