apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: api-prototyping-wf-
spec:
  entrypoint: api-prototyping-flow
  templates:
    - name: api-prototyping-flow
      steps:
        - - name: check-api
            templateRef:
              name: check-api-wt
              template: check-api
            arguments:
              parameters:
                - name: branch
                  value: players-v3
                - name: location
                  value: "workspace/apis/players-v3.yaml"
                - name: error_on
                  value: error
        - - name: document-api
            templateRef:
              name: documentation-api-wt
              template: openapi-doc
            arguments:
              parameters:
                - name: branch
                  value: players-v3
                - name: new_api_location
                  value: "workspace/apis/players-v3.yaml"
                - name: destination_folder
                  value: "/tmp/players.html"
                - name: api_name
                  value: players-v3
        - - name: catalog-api
            templateRef:
              name: api-catalog-wt
              template: api-catalog
            arguments:
              parameters:
                - name: oas-location
                  value: "workspace/apis/players-v3.yaml"
                - name: name
                  value: players-v3
                - name: lifecycle
                  value: prototyping
                - name: api-type
                  value: openapi
                - name: owner
                  value: bets
                - name: system
                  value: bets
                - name: branch
                  value: players-v3
        - - name: mocking-api
            templateRef:
              name: create-mock-wt
              template: create-mock
            arguments:
              parameters:
                - name: branch
                  value: players-v3
                - name: oas_location
                  value: "workspace/apis/players-v3.yaml"
                - name: service_name
                  value: players-v3
                - name: service_namespace
                  value: mocks
        - - name: create-pr
            templateRef:
              name: create-api-pr-prototyping-wt
              template: create-pr-proto
            arguments:
              parameters:
                - name: commit_message
                  value: "players API V5"
                - name: branch_name
                  value: "players-v3"
                - name: api_name
                  value: "players-v3"
                - name: api-context-location
                  value: "catalogs/apis/apis.yaml"
              artifacts:
                - name: catalog-file
                  from: "{{steps.catalog-api.outputs.artifacts.catalog}}"
                - name: mock-file
                  from: "{{steps.mocking-api.outputs.artifacts.ingress}}"
