apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: api-prototyping-wf-
spec:
  entrypoint: api-prototyping-flow
  templates:
    - name: api-prototyping-flow
      steps:
        - - name: check-api
            templateRef:
              name: check-api-wt
              template: check-api
            arguments:
              parameters:
                - name: branch
                  value: players-v5
                - name: location
                  value: "workspace/apis/players-v5.yaml"
                - name: error_on
                  value: error
        - - name: document-api
            templateRef:
              name: documentation-api-wt
              template: openapi-doc
            arguments:
              parameters:
                - name: branch
                  value: players-v5
                - name: new_api_location
                  value: "workspace/apis/players-v5.yaml"
                - name: destination_folder
                  value: "/tmp/players.html"
        - - name: mocking-api
            templateRef:
              name: create-mock-wt
              template: create-mock
            arguments:
              parameters:
                - name: branch
                  value: players-v5
                - name: oas_location
                  value: "workspace/apis/players-v1.yaml"
                - name: service_name
                  value: players
                - name: service_namespace
                  value: mocks
