apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: api-catalog-wt
spec:
  entrypoint: api-catalog
  templates:
    - name: api-catalog
      inputs:
        parameters:
          - name: branch
        artifacts:
          - name: apis
            path: /workspace
            git:
              repo: https://github.com/apirator/workflow-api-docs.git
              revision: "{{input.parameters.branch}}"
      arguments:
        parameters:
          - name: name
          - name: api-type
          - name: lifecycle
          - name: owner
          - name: system
          - name: oas-location
      container:
        image: claudioed/pipeline-converters:v.0.0.1
        args: ["openapi2backstage","--oas-location","{{arguments.parameters.oas-location}}","--api-type","{{arguments.parameters.api-type}}","--lifecycle","{{arguments.parameters.lifecycle}}","--owner","{{arguments.parameters.owner}}","--system","{{arguments.parameters.system}}","--name","{{arguments.parameters.name}}"]
      outputs:
        artifacts:
          - name: catalog
            path: "/tmp/{{arguments.parameters.name}}.yaml"
            archive:
              none: {}
            gcs:
              bucket: argo-artifacts-001
              key: "catalog/{{arguments.parameters.name}}.yaml"
              serviceAccountKeySecret:
                name: argo-artifact
                key: argo-development-319710-04e977a95f95.json
