apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: check-api-compatibility-wt
spec:
  entrypoint: check-api-compatibility
  templates:
    - name: check-backward-compatibility
      arguments:
        parameters:
          - name: new_api_location
          - name: old_api_location
          - name: args
      container:
        image: openapitools/openapi-diff:latest
        args: ["{{arguments.parameters.old_api_location}}","{{arguments.parameters.new_api_location}}", "{{arguments.parameters.args}}"]
