apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: documentation-api-wt
spec:
  entrypoint: openapi-doc
  templates:
    - name: openapi-doc
      inputs:
        artifacts:
          - name: apis
            path: /workspace
            git:
              repo: https://github.com/apirator/workflow-api-docs.git
              revision: "{{input.parameters.branch}}"
        parameters:
          - name: branch
      arguments:
        parameters:
          - name: new_api_location
          - name: destination_folder
          - name: api_name
      container:
        image: shesse/redoc-cli
        command: [ redoc-cli ]
        args: ["bundle","{{arguments.parameters.new_api_location}}","--output","{{arguments.parameters.destination_folder}}"]
      outputs:
        artifacts:
          - name: docs
            path: "{{arguments.parameters.destination_folder}}"
            archive:
              none: {}
            gcs:
              bucket: argo-artifacts-001
              key: "docs/{{arguments.parameters.api_name}}.html"
              serviceAccountKeySecret:
                name: argo-artifact
                key: argo-development-319710-04e977a95f95.json
