apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: documentation-api-wt
spec:
  entrypoint: openapi-doc
  templates:
    - name: openapi-doc
      inputs:
        artifacts:
          - name: apis
            path: /workspace
            git:
              repo: https://github.com/apirator/workflow-api-docs.git
              revision: "{{inputs.parameters.branch}}"
        parameters:
          - name: new_api_location
          - name: branch
      container:
        image: shesse/redoc-cli
        command: [ redoc-cli ]
        args: ["{{inputs.parameters.new_api_location}}"]
      outputs:
        artifacts:
          - name: ingress
            path: /tmp/players.yaml
            gcs:
              bucket: argo-artifacts-001
              key: docs/players.tgz
              serviceAccountKeySecret:
                name: argo-artifact
                key: argo-development-319710-04e977a95f95.json
