apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: documentation-api-wt
spec:
  entrypoint: openapi-doc
  templates:
    - name: openapi-doc
      inputs:
        artifacts:
          - name: apis
            path: /workspace
            git:
              repo: https://github.com/apirator/workflow-api-docs.git
              revision: "main"
        parameters:
          - name: new_api_location
      container:
        image: shesse/redoc-cli
        command: [ redoc-cli ]
        args: ["{{inputs.parameters.new_api_location}}"]
