apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: extract-wt
spec:
  entrypoint: extract
  templates:
    - name: extract
      inputs:
        artifacts:
          - name: apis
            path: /workspace
            git:
              repo: https://github.com/apirator/workflow-api-docs.git
              revision: "{{inputs.parameters.branch}}"
        parameters:
          - name: branch
          - name: modified
      script:
        image: mikefarah/yq:3.4.1
        command: [sh]
        source: |
          yq read /workspace/{{inputs.parameters.modified}} x-kong-name > /tmp/api-name.txt &&
          yq read /workspace/{{inputs.parameters.modified}} info.x-api-metadata.lifecycle > /tmp/lifecycle.txt
          yq read /workspace/{{inputs.parameters.modified}} info.x-api-metadata.api-type > /tmp/api-type.txt
          yq read /workspace/{{inputs.parameters.modified}} info.x-api-metadata.owner > /tmp/owner.txt
          yq read /workspace/{{inputs.parameters.modified}} info.x-api-metadata.team > /tmp/team.txt
          yq read /workspace/{{inputs.parameters.modified}} info.x-api-metadata.system > /tmp/system.txt
          yq read /workspace/{{inputs.parameters.modified}} x-kong-name > /tmp/service.txt
      outputs:
        parameters:
          - name: api-name
            valueFrom:
              default: "dummy"
              path: /tmp/api-name.txt
          - name: lifecycle
            valueFrom:
              default: "dummy"
              path: /tmp/lifecycle.txt
          - name: api-type
            valueFrom:
              default: "dummy"
              path: /tmp/api-type.txt
          - name: owner
            valueFrom:
              default: "dummy"
              path: /tmp/owner.txt
          - name: team
            valueFrom:
              default: "dummy"
              path: /tmp/team.txt
          - name: service
            valueFrom:
              default: "dummy"
              path: /tmp/service.txt
          - name: api_name
            valueFrom:
              default: "dummy"
              path: /tmp/api-name.txt
          - name: system
            valueFrom:
              default: "dummy"
              path: /tmp/system.txt

