apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: create-ingress-wt
spec:
  volumes:
    - name: oas
      configMap:
        name: oas
        items:
          - key: players-v1.yaml
            path: /apis
          - key: players-v2.yaml
            path: /apis
  entrypoint: create-ingress
  arguments:
    parameters:
      - name: oas
      - name: ingress
      - name: service
  templates:
    - name: create-ingress
      volumes:
        - name: oas
          configMap:
            name: oas
      inputs:
        parameters:
          - name: oas
          - name: ingress
          - name: service
      container:
        volumeMounts:
          - name: oas
            mountPath: /apis
        image: claudioed/openapitokongingress
        command: [oas2ingress,convert]
        args: ["--oas","{{inputs.parameters.oas}}","--ingress","{{inputs.parameters.ingress}}","--service","{{inputs.parameters.service}}"]
      outputs:
        artifacts:
          - name: ingress
            path: /tmp/players.yaml
            gcs:
              bucket: argo-artifacts-001
              key: ingresses/players.tgz
              serviceAccountKeySecret:
                name: argo-artifact
                key: argo-development-319710-04e977a95f95.json