apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: create-mock-wt
spec:
  entrypoint: create-mock
  templates:
    - name: create-mock
      inputs:
        artifacts:
          - name: apis
            path: /workspace
            git:
              repo: https://github.com/apirator/workflow-api-docs.git
              revision: "{{inputs.parameters.branch}}"
        parameters:
          - name: branch
          - name: oas_location
          - name: service_name
          - name: service_namespace
      container:
        image: claudioed/pipeline-converters:v.0.0.1
        args: ["openapi2mock","--oas-location","{{inputs.parameters.oas_location}}","--service-name","{{inputs.parameters.service_name}}","--service-namespace","{{inputs.parameters.service_namespace}}"]
      outputs:
        artifacts:
          - name: mock
            path: "/tmp/{{inputs.parameters.service_name}}.yaml"
            archive:
              none: {}
            gcs:
              bucket: argo-artifacts-001
              key: "mocks/{{inputs.parameters.service_name}}.yaml"
              serviceAccountKeySecret:
                name: argo-artifact
                key: argo-development-319710-04e977a95f95.json
