apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: create-postman-tests-wt
spec:
  entrypoint: create-postman-tests
  arguments:
    parameters:
      - name: oas
      - name: file
      - name: branch
  templates:
    - name: create-postman-tests
      inputs:
        artifacts:
          - name: apis
            path: /workspace
            git:
              repo: https://github.com/apirator/workflow-api-docs.git
              revision: "{{inputs.parameters.branch}}"
        parameters:
          - name: branch
          - name: oas
          - name: file
      container:
        image: claudioed/portman
        args: ["--local","{{inputs.parameters.oas}}","--includeTests","--bundleContractTests","--output","/tmp/{{inputs.parameters.file}}"]
      outputs:
        artifacts:
          - name: tests
            path: "/tmp/{{inputs.parameters.file}}"
            gcs:
              bucket: argo-artifacts-001
              key: "tests/{{inputs.parameters.file}}"
              serviceAccountKeySecret:
                name: argo-artifact
                key: argo-development-319710-04e977a95f95.json
