apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: create-api-pr-production-wt
spec:
  entrypoint: create-pr
  templates:
    - name: create-pr
      inputs:
        artifacts:
          - name: catalog-file
            path: /tmp/catalog.yaml
          - name: deploy-file
            path: /tmp/deploy.yaml
        parameters:
          - name: commit_message
          - name: branch_name
          - name: api_name
      script:
        image: claudioed/githucli:v.0.0.1
        command: [bash]
        env:
          - name: GH_TOKEN
            valueFrom:
              secretKeyRef:
                name: github-secret
                key: GH_TOKEN
        source: |
          git clone https://apirator:${GH_TOKEN}@github.com/apirator/workflow-manifests.git
          cd workflow-manifests && \
          git checkout -b {{inputs.parameters.branch_name}} && \
          ./usr/bin/local/pipeline-converters --help && \
          echo "writing files " && \
          cat /tmp/catalog.yaml >> catalogs/{{inputs.parameters.api_name}}.yaml && \
          cat /tmp/deploy.yaml >> apis/{{inputs.parameters.api_name}}.yaml && \
          git status && \
          echo "configuring github user" && \
          git config --global user.email "apirator@gmail.com" && \
          git config --global user.name "apirator" && \
          echo "adding files " && \
          git add catalogs/{{inputs.parameters.api_name}}.yaml && \
          git add apis/{{inputs.parameters.api_name}}.yaml && \
          git status && \
          echo "commiting files " && \
          git commit -m "new api" && \
          echo "pushing files " && \
          git push -u origin {{inputs.parameters.branch_name}} && \
          gh pr create --head {{inputs.parameters.branch_name}} --base main --title "New API " --body "API"
