apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: api-docs
  namespace: events
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  github:
    example:
      repositories:
        - owner: apirator
          names:
            - workflow-api-docs
      webhook:
        endpoint: /push
        port: "12000"
        method: POST
        url: https://api-docs-a123fedb.nip.io
      events:
        - "*"
      apiToken:
        name: github-access
        key: token
      insecure: false
      active: true
      contentType: json