apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github
  namespace: events
spec:
  template:
    serviceAccountName: github-sensor-sa
    container:
      env:
        - name: "DEBUG_LOG"
          value: "true"
  dependencies:
    - name: test-dep
      eventSourceName: api-docs
      eventName: example
      filters:
        data:
          # Name of the event that triggered the delivery: [pull_request, push, yadayadayada]
          # https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads
          - path: body.X-GitHub-Event
            type: string
            value:
              - push
  workflowTemplateRef:
    name: check-api-wt
  triggers:
    - template:
        name: github-workflow-trigger
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: api-production-wf-
              spec:
                entrypoint: api-production-flow
                templates:
                  - name: api-production-flow
                    steps:
                      - - name: check-api
                          templateRef:
                            name: check-api-wt
                            template: check-api
                          arguments:
                            parameters:
                              - name: branch
                                value: players-v5
                              - name: location
                                value: "workspace/apis/players-v5.yaml"
                              - name: error_on
                                value: error
                                ## error, warn,info and hint
                      - - name: extract-info
                          templateRef:
                            name: extract-wt
                            template: extract
                          arguments:
                            parameters:
                              - name: branch
                                value: players-v10
                              - name: modified
                                value: "/apis/players-v10.yaml"
                      - - name: catalog-api
                          templateRef:
                            name: api-catalog-wt
                            template: api-catalog
                          arguments:
                            parameters:
                              - name: oas-location
                                value: "workspace/apis/players-v5.yaml"
                              - name: name
                                value: "{{steps.extract-info.outputs.parameters.api-name}}"
                              - name: lifecycle
                                value: "{{steps.extract-info.outputs.parameters.lifecycle}}"
                              - name: api-type
                                value: "{{steps.extract-info.outputs.parameters.api-type}}"
                              - name: owner
                                value: "{{steps.extract-info.outputs.parameters.owner}}"
                              - name: system
                                value: "{{steps.extract-info.outputs.parameters.system}}"
                              - name: branch
                                value: players-v5
                      - - name: document-api
                          templateRef:
                            name: documentation-api-wt
                            template: openapi-doc
                          arguments:
                            parameters:
                              - name: branch
                                value: players-v5
                              - name: new_api_location
                                value: "workspace/apis/players-v5.yaml"
                              - name: destination_folder
                                value: "/tmp/players.html"
                              - name: api_name
                                value: "{{steps.extract-info.outputs.parameters.api_name}}"
                      - - name: deploy-api
                          templateRef:
                            name: create-ingress-wt
                            template: create-ingress
                          arguments:
                            parameters:
                              - name: branch
                                value: players-v5
                              - name: oas
                                value: "/workspace/apis/players-v5.yaml"
                              - name: ingress
                                value: /tmp
                              - name: service
                                value: "{{steps.extract-info.outputs.parameters.api-name}}"
                      - - name: create-pr
                          templateRef:
                            name: create-api-pr-production-wt
                            template: create-pr
                          arguments:
                            parameters:
                              - name: commit_message
                                value: "players API V5"
                              - name: branch_name
                                value: "players-v5"
                              - name: api_name
                                value: "{{steps.extract-info.outputs.parameters.api-name}}"
                              - name: api-context-location
                                value: "catalogs/apis/apis.yaml"
                            artifacts:
                              - name: catalog-file
                                from: "{{steps.catalog-api.outputs.artifacts.catalog}}"
                              - name: deploy-file
                                from: "{{steps.deploy-api.outputs.artifacts.ingress}}"

          parameters:
            # branch
            - src:
                dependencyName: test-dep
                dataKey: body.ref
              dest: spec.templates.0.steps.0.0.arguments.parameters.0.value
            - src:
                dependencyName: test-dep
                dataKey: body.ref
              dest: spec.templates.0.steps.1.0.arguments.parameters.0.value
            - src:
                dependencyName: test-dep
                dataKey: body.ref
              dest: spec.templates.0.steps.2.0.arguments.parameters.6.value
            - src:
                dependencyName: test-dep
                dataKey: body.ref
              dest: spec.templates.0.steps.3.0.arguments.parameters.0.value
            - src:
                dependencyName: test-dep
                dataKey: body.ref
              dest: spec.templates.0.steps.4.0.arguments.parameters.0.value
            - src:
                dependencyName: test-dep
                dataKey: body.ref
              dest: spec.templates.0.steps.5.0.arguments.parameters.1.value

            # commits
            - src:
                dependencyName: test-dep
                dataTemplate:  "workspace/{{ first .Input.body.head_commit.added }}"
              dest: spec.templates.0.steps.0.0.arguments.parameters.1.value
            - src:
                dependencyName: test-dep
                dataTemplate:  "/{{ first .Input.body.head_commit.added }}"
              dest: spec.templates.0.steps.1.0.arguments.parameters.1.value
            - src:
                dependencyName: test-dep
                dataTemplate:  "workspace/{{ first .Input.body.head_commit.added }}"
              dest: spec.templates.0.steps.2.0.arguments.parameters.0.value
            - src:
                dependencyName: test-dep
                dataTemplate:  "workspace/{{ first .Input.body.head_commit.added }}"
              dest: spec.templates.0.steps.3.0.arguments.parameters.1.value
            - src:
                dependencyName: test-dep
                dataTemplate:  "/workspace/{{ first .Input.body.head_commit.added }}"
              dest: spec.templates.0.steps.4.0.arguments.parameters.1.value
      retryStrategy:
        steps: 3
