apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github
  namespace: events
spec:
  template:
    serviceAccountName: github-sensor-sa
    container:
      env:
        - name: "DEBUG_LOG"
          value: "true"
  dependencies:
    - name: test-dep
      eventSourceName: api-docs
      eventName: example
      filters:
        data:
          # Name of the event that triggered the delivery: [pull_request, push, yadayadayada]
          # https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads
          - path: body.X-GitHub-Event
            type: string
            value:
              - pull_request
          - path: body.action
            type: string
            value:
              - opened
              - edited
              - reopened
              - synchronize
          - path: body.pull_request.state
            type: string
            value:
              - open
          - path: body.pull_request.base.ref
            type: string
            value:
              - main
  workflowTemplateRef:
    name: check-api-wt
  triggers:
    - template:
        name: github-workflow-trigger
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: check-api-wf-
              spec:
                entrypoint: check-api
                arguments:
                  parameters:
                    - name: location
                      value: "workspace/apis/players-v1.yaml"
                    - name: error_on
                      value: info
                      ## error, warn,info and hint
                workflowTemplateRef:
                  name: check-api-wt
          parameters:
            - src:
                dependencyName: test-dep
                dataKey: body.pull_request.title
              dest: spec.arguments.parameters.0.value
      retryStrategy:
        steps: 3