apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: github-sensor-role
  namespace: events
rules:
  - apiGroups:
      - argoproj.io
    verbs:
      - "*"
    resources:
      - workflows
      - workflowtemplates
      - cronworkflows
      - clusterworkflowtemplates